runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 2

env_variables:
  GCS_AUTH_FILE: auth.json

endpoints_api_service:
  name: mark-edmondson-usa.appspot.com
  config_id: 2017-08-03r1